[LMS-229] Update notebook dependencies
Ed-Fi-Alliance-OSS/LMS-Toolkit pull request #176
Opened 2021-04-12 18:21 UTC by bradbanister

There were issues found with notebooks and the GC extractor unrelated to Python 3.9, which I'll put in separate tickets.

2021-04-12 21:07 UTC, stephenfuqua requested changes
Everything seems fine so far... except that each `pyproject.toml` still has this:

```
[tool.poetry.dependencies]
python = "^3.8"
```

Seems like we should update that...

2021-04-12 21:16 UTC, bradbanister commented
> Everything seems fine so far... except that each `pyproject.toml` still has this:
> 
> ```
> [tool.poetry.dependencies]
> python = "^3.8"
> ```
> 
> Seems like we should update that...

I thought about that but wasn't sure we wanted to make that restriction. The ticket was originally to ensure everything ran on 3.9. Do we now only support 3.9?

2021-04-12 21:24 UTC, stephenfuqua commented
> I thought about that but wasn't sure we wanted to make that restriction. The ticket was originally to ensure everything ran on 3.9. Do we now only support 3.9?

The readme updates state that 3.9 is required. I think it will be too confusing for us to maintain both 3.8 and 3.9 right now, as we would need to be able to switch back and forth easily to run tests.

2021-04-13 15:31 UTC, stephenfuqua approved these changes

2021-04-13 15:31 UTC, merged